// Run through tests/Run-Tests.ps1 -Suites TabShadow (STA + Application.Run).
// Creates temporary test HWNDs outside the desktop; does not alter running groups.
#r "System.Drawing"
#r "Debug/Win32.dll"
#r "Debug/WindowTabs.exe"

open System
open System.Drawing
open System.Drawing.Imaging
open System.Runtime.InteropServices
open Bemo
open Bemo.Win32.Forms

let referenceShadow width height (mask:byte[]) padding =
    let w = width + padding * 2
    let h = height + padding
    let sigma = float padding / 3.0
    let weights = Array.init (padding * 2 + 1) (fun i ->
        let d = float (i - padding)
        exp (-d * d / (2.0 * sigma * sigma)))
    let total = Array.sum weights
    let kernel = weights |> Array.map (fun v -> v / total)
    let sample x y =
        let sx = x - padding
        let sy = y - padding
        if sx < 0 || sx >= width || sy < 0 || sy >= height then 0.0
        else float mask.[sy * width + sx] / 255.0
    let horizontal = Array.zeroCreate<float> (w * h)
    for y in padding .. h - 1 do
        for x in 0 .. w - 1 do
            let mutable v = 0.0
            for k in -padding .. padding do
                v <- v + sample (x + k) y * kernel.[k + padding]
            horizontal.[y * w + x] <- v
    let pixels = Array.zeroCreate<byte> (w * h * 4)
    // Fade the side tails into the window junction. No bottom shadow row.
    let fadeHeight = max 1 (padding / 3)
    for y in 0 .. h - 1 do
        let fade = min 1.0 (float (h - 1 - y) / float fadeHeight)
        for x in 0 .. w - 1 do
            let mutable v = 0.0
            for k in -padding .. padding do
                let sy = y + k
                if sy >= 0 && sy < h then
                    v <- v + horizontal.[sy * w + x] * kernel.[k + padding]
            // The helper is owned by (and above) the strip; cut the tabs out.
            let exterior = 1.0 - sample x y
            pixels.[(y * w + x) * 4 + 3] <- byte (Math.Round(64.0 * v * exterior * fade))
    let bitmap = new Bitmap(w, h, PixelFormat.Format32bppArgb)
    let data = bitmap.LockBits(Rectangle(0, 0, w, h), ImageLockMode.WriteOnly, PixelFormat.Format32bppArgb)
    try
        for y in 0 .. h - 1 do
            Marshal.Copy(pixels, y * w * 4, IntPtr.Add(data.Scan0, y * data.Stride), w * 4)
    finally
        bitmap.UnlockBits(data)
    bitmap


let main () =
    let check condition message = if not condition then failwith message
    let pixels (bitmap:Bitmap) =
        let data = bitmap.LockBits(Rectangle(0,0,bitmap.Width,bitmap.Height),ImageLockMode.ReadOnly,PixelFormat.Format32bppArgb)
        try
            let bytes = Array.zeroCreate<byte> (bitmap.Width*bitmap.Height*4)
            for y in 0..bitmap.Height-1 do
                Marshal.Copy(IntPtr.Add(data.Scan0,y*data.Stride),bytes,y*bitmap.Width*4,bitmap.Width*4)
            bytes
        finally bitmap.UnlockBits(data)
    let renderer = TabShadow.Renderer()
    let random = Random(42)
    // Compare every alpha value with the original convolution, including
    // partial alpha, direction changes and reused buffers after larger frames.
    for width,height,padding in [315,42,22;160,26,15;40,12,3;280,35,20;60,18,8] do
      for partial in [false;true] do
        let mask = Array.init (width*height) (fun i ->
            if partial then byte(random.Next(256))
            elif i%width>width/5 && i%width<width*4/5 && i/width>1 then 255uy else 0uy)
        for direction in [TabUp;TabDown] do
            let input = if direction=TabUp then mask else Array.init mask.Length (fun i -> mask.[(height-1-i/width)*width+i%width])
            use expected = referenceShadow width height input padding
            if direction=TabDown then expected.RotateFlip(RotateFlipType.RotateNoneFlipY)
            use actual = renderer.Render(width,height,mask,padding,direction)
            check (pixels actual = pixels expected) "Optimized shadow pixels differ from the original convolution"
    let padding = 15
    let width, height = 160, 26
    let mask = Array.init (width * height) (fun i ->
        let x, y = i % width, i / width
        if x >= 20 && x < 140 && y >= 1 && y < height - 1 then 255uy else 0uy)
    use empty = TabShadow.render width height (Array.zeroCreate (width * height)) padding
    check (TabShadow.silhouette empty |> Array.forall ((=) 0uy)) "Empty strip casts a shadow"
    use hitArea = new Bitmap(width, height)
    do
        use g = Graphics.FromImage(hitArea)
        g.Clear(Color.FromArgb(1, 1, 1, 1))
    check (TabShadow.silhouette hitArea |> Array.forall ((=) 0uy)) "Hit-test background casts a shadow"

    // A preview generated by the actual tab renderer, on white and dark backgrounds.
    let appearance : TabAppearanceInfo = {
        tabStyle=JoinedTabs; tabHeight=26; tabMaxWidth=210; tabOverlap=0; tabHeightOffset=0
        tabIndentFlipped=0; tabIndentNormal=0; tabTextColor=Color.Black; tabFlashBgColor=Color.Orange
        tabNormalBgColor=Color.FromArgb(204,204,204)
        tabActiveBgColor=Color.White; tabHighlightBgColor=Color.FromArgb(228,228,228)
        tabBorderColor=Color.FromArgb(168,168,168) }
    let info text : TabDisplayInfo = {
        tint=None; colorStyle="Stripe"; numberBadge=None; bgColor=None; text=text; icon=SystemIcons.Application
        textFont=SystemFonts.MenuFont; textBrush=Brushes.Black }
    let ts : TabStripSprite<int> = {
        tabs=Map2(List2([1,info "Active tab"; 2,info "Another window"]))
        lorder=List2([1;2]); zorder=List2([1;2]); size=Sz(420,28)
        slide=None; direction=TabUp; alignment=TabLeft; onlyIcons=false; held=None; centerShift=0.0
        transparent=true; appearance=appearance; hover=None; captured=None }
    for appearance in [Theme.light;Theme.dark] do
        for icons in [false;true] do
            let badges = { ts with appearance=appearance;onlyIcons=icons;tabs=Map2(List2([1,{info "One" with numberBadge=Some "1"};2,{info "Ten" with numberBadge=Some "A"}])) }
            let drawn = badges.sprite.children.list |> List.collect(fun (_,tab) -> tab.children.list) |> List.choose(fun (_,child) -> match child with :? NumberBadgeSprite as badge -> Some badge | _ -> None)
            check (drawn.Length=1 && drawn.Head.label="A") "Active tab hint was shown or inactive letter hint was missing"
    for appearance in [Theme.light;Theme.dark] do
        for style in [JoinedTabs;FolderTabs;PillTabs] do
            for colorStyle in ["Stripe";"Fill"] do
                let tinted = { ts with appearance={appearance with tabStyle=style}; tabs=Map2(List2([1,{info "One" with tint=Some Color.Blue;colorStyle=colorStyle};2,{info "Two" with tint=Some Color.Blue;colorStyle=colorStyle}])) }
                let tabs = tinted.sprite.children.list |> List.choose(fun (_,child) -> match child with :? TabSprite<int> as tab -> Some tab | _ -> None)
                let active,inactive = tabs |> List.find(fun t -> t.isTop),tabs |> List.find(fun t -> not t.isTop)
                check (not inactive.isRaised) "Tint raised an inactive tab"
                if colorStyle="Fill" then
                    // The active tab in its colour exactly as chosen, the others darker shades of it
                    // with less colour. Colours pushed lighter or darker for the text came out muddy.
                    let text = appearance.tabTextColor
                    let hovered = {inactive with hover=Some TabBackground}
                    check (active.fillColor=Color.Blue) "A fill changed the colour of the active tab"
                    check (inactive.fillColor=Theme.tabShade 0.12 0.6 Color.Blue) "An inactive filled tab is not a darker, quieter shade of its colour"
                    check (hovered.fillColor=Theme.tabShade 0.06 0.75 Color.Blue) "Hovering a filled tab gives no feedback"
                    check (TextContrast.luminance inactive.fillColor<TextContrast.luminance hovered.fillColor &&
                           TextContrast.luminance hovered.fillColor<TextContrast.luminance active.fillColor) "The active filled tab is not the brightest"
                    // The text gives way instead, chosen for the colour whatever the text setting says:
                    // white where it reads better, as on every palette colour, otherwise dark.
                    let own = if TextContrast.ratio Color.White Color.Blue>=TextContrast.ratio Theme.light.tabTextColor Color.Blue then Color.White else Theme.light.tabTextColor
                    check (active.textColor=TextContrast.readable own Color.Blue && hovered.textColor=active.textColor)
                          "The active or hovered filled tab does not take the text that reads on its colour"
                    // Tabs behind grey theirs a little, still readable; light or dark never flips.
                    let darker (tab:TabSprite<int>) = TextContrast.luminance tab.textColor < TextContrast.luminance tab.fillColor
                    check ((own<>Color.White || inactive.textColor=Theme.inactiveFillText) && inactive.textColor<>active.textColor && darker inactive=darker active &&
                           TextContrast.ratio inactive.textColor inactive.fillColor>=TextContrast.minimum)
                          "Text behind the active filled tab does not grey, flipped, or became hard to read"
                    // Grey text reads on neither a light nor a deep colour: the colour stays, the text goes.
                    let greyAppearance = {appearance with tabStyle=style; tabTextColor=Color.FromRGB(0x929292)}
                    let grey = { tinted with appearance=greyAppearance; tabs=Map2(List2([1,{info "One" with tint=Some Color.Orange;colorStyle="Fill"};2,{info "Two" with tint=Some Color.Orange;colorStyle="Fill"}])) }
                    let greyActive = grey.sprite.children.list |> List.pick(fun (_,child) -> match child with :? TabSprite<int> as tab when tab.isTop -> Some tab | _ -> None)
                    check (greyActive.fillColor=Color.Orange && TextContrast.ratio greyActive.textColor Color.Orange>=TextContrast.minimum)
                          "Unreadable text changed the tab's colour instead of its own"
                else
                    check (active.fillColor<>inactive.fillColor) "Tint hid the active tab"
                    check (inactive.fillColor=appearance.tabNormalBgColor) "A stripe mixed its color into the tab"
                for tab in tabs do check (TextContrast.ratio tab.textColor tab.fillColor>=4.5) "Tint made text unreadable"
                let flash = {inactive with displayInfo={inactive.displayInfo with bgColor=Some Color.Orange}}
                check (flash.fillColor=Color.Orange) "Tint overrode attention"
    check (Theme.tabTint true (Some Color.Red)=None) "High contrast retained tint"
    let tabImage = ts.render
    // Short tabs shrink their contents to fit instead of clipping them.
    for h in [12;18;26] do
        use font = TabMetrics.font h FontStyle.Regular
        check (font.Height <= max h (SystemFonts.MenuFont.Height)) (sprintf "Text line does not fit a %dpx tab" h)
        let info text : TabDisplayInfo = { tint=None; colorStyle="Stripe"; numberBadge=None; bgColor=None; text=text; icon=SystemIcons.Application; textFont=font; textBrush=Brushes.Black }
        let strip = { ts with appearance={ appearance with tabHeight=h }; size=Sz(420,h+1)
                              tabs=Map2(List2([1,info "Active tab"; 2,info "Another window"])) }
        for _,tab in strip.sprite.children.list do
            for location,child in tab.children.list do
                let size = match child with :? IconSprite as icon -> icon.size | :? CloseButtonSprite as close -> close.size | _ -> Sz(0,0)
                check (location.y >= 0 && location.y+size.height <= h) (sprintf "Icon or close button overflows a %dpx tab" h)
    // Icons only: the icon is centred; a smaller close button shows beside it on the pointed-at
    // tab only, and not at all when the tab is too narrow for both.
    do
        let parts (strip:TabStripSprite<int>) =
            strip.sprite.children.list |> List.map(fun (_,tab) ->
                let tab = tab :?> TabSprite<int>
                let find kind = (tab :> ISprite).children.list |> List.tryPick(fun (location,child:ISprite) -> kind location child)
                let icon = find (fun location child -> match child with :? IconSprite as icon -> Some(location,icon.size) | _ -> None)
                let close = find (fun location child -> match child with :? CloseButtonSprite as close -> Some(location,close.size) | _ -> None)
                tab.id,tab.size,icon.Value,close)
        // As TabStrip sizes icon-only tabs.
        let icons = { ts with onlyIcons=true; appearance={ appearance with tabMaxWidth=Dpi.scale 50 } }
        for _,size,(location,icon),close in parts icons do
            check (abs (location.x+icon.width/2-size.width/2) <= 1) "An icon-only tab does not centre its icon"
            check close.IsNone "An icon-only tab shows a close button without the pointer"
        let pointed = parts { icons with hover=Some(2,TabBackground) }
        for id,size,(icon,iconSize),close in pointed do
            match close with
            | Some(location,closeSize) ->
                check (id=2) "An icon-only tab the pointer is not on shows a close button"
                check (location.x >= icon.x+iconSize.width && location.x+closeSize.width <= size.width) "The close button overlaps the centred icon"
                check (closeSize.width < iconSize.width) "The icon-only close button is not smaller than the icon"
            | None -> check (id<>2) "The pointed-at icon-only tab shows no close button"
        let narrow = parts { icons with appearance={ appearance with tabMaxWidth=Dpi.scale 30 }; hover=Some(2,TabBackground) }
        check (narrow |> List.forall(fun (_,_,_,close) -> close.IsNone)) "A tab too narrow for icon and button shows a close button"
    // Many tabs: titles give way to icons, tabs stop at a clickable width and the first stays in view.
    do
        let strip count = { ts with alignment=TabCenter; size=Sz(420,28)
                                    tabs=Map2(List2([for i in 1..count -> i,info "Window"]))
                                    lorder=List2([1..count]); zorder=List2([1..count]) }
        let tabs (s:TabStripSprite<int>) = s.sprite.children.list |> List.map(fun (location,tab) -> location,(tab :?> TabSprite<int>))
        check (not (strip 3).isCompact && (tabs (strip 3)) |> List.forall(fun (_,tab) -> not tab.onlyIcon)) "Three tabs lost their titles"
        check ((strip 6).isCompact && (tabs (strip 6)) |> List.forall(fun (_,tab) -> tab.onlyIcon)) "Tabs too narrow for a title kept it"
        let crowded = tabs (strip 40)
        let minimum = TabMetrics.iconSide 26 + 2*TabMetrics.scaled 26 6
        check (crowded |> List.forall(fun (_,tab) -> tab.size.width >= minimum)) "Crowded tabs shrank below a clickable width"
        check (crowded |> List.forall(fun (location,_) -> location.x >= 0)) "Crowded centred tabs pushed the first tab out of view"
        let held = { strip 3 with held=Some(100.0,60.0) }
        let first = tabs held |> List.find(fun (_,tab) -> tab.id=1)
        check ((fst first).x=60 && (snd first).size.width=100) "A held layout moved the tabs after a close"
        let overflowing = { strip 5 with held=Some(100.0,60.0) }
        check ((tabs overflowing) |> List.forall(fun (_,tab) -> tab.size.width<100)) "A held layout that no longer fits was kept"
        // Inside the title bar centred tabs centre on the window, not the narrower strip; once
        // they fill the row they keep the caption buttons' room free on both sides.
        let span (s:TabStripSprite<int>) =
            let all = tabs s
            all |> List.map(fun (location,_) -> location.x) |> List.min,
            all |> List.map(fun (location,tab) -> location.x+tab.size.width) |> List.max
        let wide count = { strip count with size=Sz(800,28) }
        let left,right = span { wide 2 with centerShift=40.0 }
        let plainLeft,plainRight = span (wide 2)
        check (left-plainLeft=40 && right-plainRight=40) "Centred tabs in the title bar did not centre on the window"
        let crowdedLeft,crowdedRight = span { wide 6 with centerShift=40.0 }
        check (crowdedRight = 800) "Centred tabs ran into the caption buttons or left the row unfilled"
        check (crowdedLeft = 80) "Centred tabs that fill the row are not symmetric about the window"
    // Folder and pill styles: the inactive tabs are the bar, the active tab a shape raised on it.
    // Three 140px tabs, the middle one active, each 27px tall from y=1.
    do
        let strip style = { ts with appearance={ appearance with tabStyle=style }
                                    tabs=Map2(List2([1,info "Window"; 2,info "Window"; 3,info "Window"]))
                                    lorder=List2([1;2;3]); zorder=List2([2;1;3]) }
        // Tabs a fraction of a pixel wide, up and down: every column from the first tab to the last
        // is covered, or the window behind shows through as a dark line beside the active tab.
        for direction in [TabUp;TabDown] do
            for style in [JoinedTabs;PillTabs;FolderTabs] do
                let uneven = { strip style with size=Sz(637,28); direction=direction
                                                appearance={ appearance with tabStyle=style; tabMaxWidth=400 } }
                use bitmap = uneven.render.bitmap
                let spans = uneven.tabSprites.list |> List.map(fun (location,tab) -> location.x,location.x+tab.size.width)
                let left,right = spans |> List.map fst |> List.min,spans |> List.map snd |> List.max
                check (right-left>=636 && [left..right-1] |> List.forall(fun x -> bitmap.GetPixel(x,14).A=255uy))
                    (sprintf "A column between %A tabs facing %A is left uncovered" style direction)
        let folder = strip FolderTabs
        check (match folder.tryHit(Pt(138,26)) with Some(1,_) -> true | _ -> false) "A folder tab's foot takes the pointer from the tab beneath it"
    let originalDpi = Dpi.value()
    try
        for dpi in [96;144;192] do
            Dpi.set dpi
            let close : ISprite =
                { CloseButtonSprite.hover=false; captured=false; foreColor=Color.Black; size=Dpi.scaleSize(Sz(16,16)) } :> ISprite
            let extent = Dpi.scale 16
            use closePixels = close.image.bitmap
            check (closePixels.GetPixel(1,1).A=0uy) "Close hit-test test point is not transparent"
            for x,y in [1,1;extent-2,1;1,extent-2;extent-2,extent-2;extent/2,extent/2] do
                check (not (close.hit(Pt(x,y))).isEmpty) "Transparent area of close button cannot be clicked"
            for x,y in [-1,0;0,-1;extent,0;0,extent] do
                check ((close.hit(Pt(x,y))).isEmpty) "Close button captures neighboring pixels"
            for direction in [TabUp;TabDown] do
                let strip = { ts with appearance=appearance.scaled; size=Dpi.scaleSize(Sz(420,28)); direction=direction }
                use bar = strip.renderCollapsed.bitmap
                check (bar.Height=Dpi.scale 4 && bar.Width=strip.size.width) "Minimal bar does not scale with DPI"
                let expectedOffset = if direction=TabUp then strip.size.height-bar.Height else 0
                check (strip.collapsedOffset=expectedOffset) "Minimal bar is not at the window edge"
                check (bar.GetPixel(Dpi.scale 80,bar.Height/2).A=255uy) "Minimal bar lacks a solid hover target"
                let sameColor (a:Color) (b:Color) = a.ToArgb()=b.ToArgb()
                let pixel (bar:Bitmap) x = bar.GetPixel(x,bar.Height/2)
                let segment (strip:TabStripSprite<int>) id =
                    strip.sprite.children.list |> List.pick(fun (location,sprite) ->
                        let tab = sprite :?> TabSprite<int>
                        if tab.id=id then Some(location.x,tab.size.width) else None)
                let three = { strip with tabs=Map2(List2([1,info "One";2,info "Two";3,info "Three"])); lorder=List2([2;1;3]); zorder=List2([1;2;3]) }
                // A tab calling for attention shows its flashing colour in the bar as well.
                let flashing = { three with tabs=Map2(List2([1,info "One";2,{ info "Two" with bgColor=Some appearance.tabFlashBgColor };3,info "Three"])) }
                use flashingBar = flashing.renderCollapsed.bitmap
                let x,width = segment flashing 2
                check (sameColor (pixel flashingBar (x+width/2)) appearance.tabFlashBgColor) "A flashing tab does not show in the minimal bar"
                check ((strip.tryHit(Pt(Dpi.scale 80,strip.collapsedOffset+bar.Height/2))).IsSome) "Minimal bar cannot reveal its tabs"
                let tabLocation,tabSprite = strip.sprite.children.list |> List.find(fun (_,sprite) -> sprite.children.list |> List.exists(fun (_,child) -> child :? CloseButtonSprite))
                let closeLocation,_ = tabSprite.children.list |> List.find(fun (_,child) -> child :? CloseButtonSprite)
                let point = tabLocation.add(closeLocation).add(Pt(1,1))
                check (strip.tryHit(point) |> Option.exists(fun (_,part) -> part=TabClose)) "Strip does not route the full close-button region to close"
    finally Dpi.set originalDpi
    use tabBitmap = tabImage.bitmap
    printfn "Rendering checks passed."

    // Real HWNDs outside the desktop: ownership, flags, move/hide/restore and cleanup.
    let os = OS()
    let mutable helper : TabShadowWindow option = None
    let handler (msg:Win32Message) =
        let result = msg.def()
        if msg.msg = WindowMessages.WM_WINDOWPOSCHANGED then
            helper |> Option.iter (fun shadow -> shadow.sync())
        result
    let owner = os.createWindow handler WindowsStyles.WS_POPUP WindowsExtendedStyles.WS_EX_LAYERED
    try
        let foreground = os.foreground.hwnd
        let ownerWindow = os.windowFromHwnd(owner.hwnd)
        let layer = new TabShadowWindow(os, owner.hwnd)
        helper <- Some layer
        try
            ownerWindow.update(tabImage, Pt(-10000,-10000), 255uy)
            layer.update(tabImage, 255uy, TabUp)
            let owned = os.windowsInZorder.list |> List.find (fun w -> w.parent.hwnd = owner.hwnd)
            let hwnd = owned.hwnd
            check owned.isVisible "Shadow not shown"
            check (owned.hasStyleEx WindowsExtendedStyles.WS_EX_TRANSPARENT) "Shadow intercepts clicks"
            check (owned.hasStyleEx WindowsExtendedStyles.WS_EX_NOACTIVATE) "Shadow can activate"
            check (owned.hasStyleEx WindowsExtendedStyles.WS_EX_TOOLWINDOW) "Shadow is not a tool window"
            check (not owned.isTopMost) "Shadow is globally topmost"
            let distance = Dpi.scale 15
            check (owned.location.x = -10000-distance) "Wrong initial position"
            // SetWindowPos notifies the owner; layered bitmap updates refresh
            // both layers explicitly, as TabStrip.update does.
            let move x y =
                WinUserApi.SetWindowPos(owner.hwnd, IntPtr.Zero, x, y, 0, 0,
                    SetWindowPosFlags.SWP_NOSIZE ||| SetWindowPosFlags.SWP_NOACTIVATE |||
                    SetWindowPosFlags.SWP_NOZORDER) |> ignore
            move -9900 -9800
            check (owned.location.x = -9900-distance && owned.location.y = -9800-distance) "Shadow did not follow"
            ownerWindow.hide()
            check (not owned.isVisible) "Shadow left behind after hide"
            ownerWindow.showNoActivate()
            check owned.isVisible "Shadow not restored"
            // Simulate Windows hiding the owned popup after a frame update.
            // The deferred activation refresh must recover even with no new bitmap.
            owned.hide()
            check (not owned.isVisible) "Could not simulate hidden owned popup"
            layer.sync()
            check owned.isVisible "Activation sync did not restore the shadow"
            check (ownerWindow.prevZorder.hwnd = hwnd) "Shadow not adjacent to strip"
            layer.hide()
            move -9800 -9700
            check (not owned.isVisible) "Disabled shadow reappeared"
            ownerWindow.update(tabImage, Pt(-9700,-9600), 128uy)
            layer.update(tabImage, 128uy, TabUp)
            check (owned.location.x = -9700-distance && owned.location.y = -9600-distance) "Layered update did not follow"
            check (os.foreground.hwnd = foreground) "Shadow changed foreground"
            layer.update(tabImage, 255uy, TabDown)
            check (owned.location.y = -9600) "Down shadow offset is wrong"
            move -9600 -9500
            check (owned.location.y = -9500) "Down shadow did not follow"
            layer.update(tabImage, 255uy, TabUp)
            check (owned.location.y = -9500-distance) "Restore did not reset shadow direction"
            (layer :> IDisposable).Dispose()
            helper <- None
            check (not (WinUserApi.IsWindow(hwnd))) "Shadow HWND leaked"
            printfn "Native window lifecycle checks passed."
        finally
            if helper.IsSome then
                helper <- None
                (layer :> IDisposable).Dispose()
    finally
        (owner :?> IDisposable).Dispose()
TestInit.run main
