// From the repository root, build a separate Debug output (Release is statically linked):
// dotnet build WtProgram/WtProgram.fsproj -c Debug -p:OutDir=<absolute-path-to-tests/Debug/>
// Then run: fsi --exec tests/TabShadow.fsx
// Creates temporary test HWNDs outside the desktop; does not alter running groups.
#r "System.Drawing"
#r "Debug/Win32.dll"
#r "Debug/WindowTabs.exe"

open System
open System.Drawing
open System.Drawing.Imaging
open Bemo
open Bemo.Win32.Forms

let main () =
    let check condition message = if not condition then failwith message
    let padding = 15
    let width, height = 160, 26
    let mask = Array.init (width * height) (fun i ->
        let x, y = i % width, i / width
        if x >= 20 && x < 140 && y >= 1 && y < height - 1 then 255uy else 0uy)
    use shadow = TabShadow.render width height mask padding
    check (shadow.Width = width + padding * 2 && shadow.Height = height + padding) "Unexpected padding"
    let alpha x y = int (shadow.GetPixel(x, y).A)
    check (alpha (padding + 80) (padding - 1) > 0) "Missing top shadow"
    check (alpha (padding + 19) (padding + 10) > 0) "Missing side shadow"
    for y in 0 .. shadow.Height - 1 do
        for x in 0 .. shadow.Width - 1 do
            check (alpha x y = alpha (shadow.Width - 1 - x) y) "Asymmetric shadow"
            if y = shadow.Height - 1 then check (alpha x y = 0) "Bottom shadow line"
            if x >= padding && x < padding + width && y >= padding then
                if mask.[(y - padding) * width + x - padding] = 255uy then
                    check (alpha x y = 0) "Shadow overlaps a tab"
    for y in 1 .. padding - 1 do
        let previous = alpha (padding + 80) (y - 1)
        let current = alpha (padding + 80) y
        check (current >= previous && current - previous <= 6) "Hard edge in gradient"
    use downShadow = TabShadow.renderForDirection width height mask padding TabDown
    for y in 0 .. downShadow.Height - 1 do
        for x in 0 .. downShadow.Width - 1 do
            check (downShadow.GetPixel(x,y).A = shadow.GetPixel(x,shadow.Height-1-y).A) "Down shadow is not mirrored"
    check (downShadow.GetPixel(padding+80,height+1).A > 0uy) "Missing lower shadow"
    for x in 0 .. downShadow.Width-1 do
        check (downShadow.GetPixel(x,0).A = 0uy) "Top attachment seam"
    use empty = TabShadow.render width height (Array.zeroCreate (width * height)) padding
    check (TabShadow.silhouette empty |> Array.forall ((=) 0uy)) "Empty strip casts a shadow"
    use hitArea = new Bitmap(width, height)
    do
        use g = Graphics.FromImage(hitArea)
        g.Clear(Color.FromArgb(1, 1, 1, 1))
    check (TabShadow.silhouette hitArea |> Array.forall ((=) 0uy)) "Hit-test background casts a shadow"

    // A preview generated by the actual tab renderer, on white and dark backgrounds.
    let appearance : TabAppearanceInfo = {
        tabHeight=26; tabMaxWidth=210; tabOverlap=0; tabHeightOffset=0
        tabIndentFlipped=0; tabIndentNormal=0; tabTextColor=Color.Black; tabFlashBgColor=Color.Orange
        tabNormalBgColor=Color.FromArgb(204,204,204)
        tabActiveBgColor=Color.White; tabHighlightBgColor=Color.FromArgb(228,228,228)
        tabBorderColor=Color.FromArgb(168,168,168) }
    let info text : TabDisplayInfo = {
        bgColor=None; text=text; icon=SystemIcons.Application
        textFont=SystemFonts.MenuFont; textBrush=Brushes.Black }
    let ts : TabStripSprite<int> = {
        tabs=Map2(List2([1,info "Active tab"; 2,info "Another window"]))
        lorder=List2([1;2]); zorder=List2([1;2]); size=Sz(420,28)
        slide=None; direction=TabUp; alignment=TabLeft; onlyIcons=false
        transparent=true; appearance=appearance; hover=None; captured=None }
    let tabImage = ts.render
    let originalDpi = Dpi.value()
    try
        for dpi in [96;144;192] do
            Dpi.set dpi
            let close : ISprite =
                { CloseButtonSprite.hover=false; captured=false; foreColor=Color.Black; size=Dpi.scaleSize(Sz(16,16)) } :> ISprite
            let extent = Dpi.scale 16
            use closePixels = close.image.bitmap
            check (closePixels.GetPixel(1,1).A=0uy) "Close hit-test test point is not transparent"
            for x,y in [1,1;extent-2,1;1,extent-2;extent-2,extent-2;extent/2,extent/2] do
                check (not (close.hit(Pt(x,y))).isEmpty) "Transparent area of close button cannot be clicked"
            for x,y in [-1,0;0,-1;extent,0;0,extent] do
                check ((close.hit(Pt(x,y))).isEmpty) "Close button captures neighboring pixels"
            for direction in [TabUp;TabDown] do
                let strip = { ts with appearance=appearance.scaled; size=Dpi.scaleSize(Sz(420,28)); direction=direction }
                use bar = strip.renderCollapsed.bitmap
                check (bar.Height=Dpi.scale 4 && bar.Width=strip.size.width) "Minimal bar does not scale with DPI"
                let expectedOffset = if direction=TabUp then strip.size.height-bar.Height else 0
                check (strip.collapsedOffset=expectedOffset) "Minimal bar is not at the window edge"
                check (bar.GetPixel(Dpi.scale 80,bar.Height/2).A=255uy) "Minimal bar lacks a solid hover target"
                check ((strip.tryHit(Pt(Dpi.scale 80,strip.collapsedOffset+bar.Height/2))).IsSome) "Minimal bar cannot reveal its tabs"
                let tabLocation,tabSprite = strip.sprite.children.list |> List.find(fun (_,sprite) -> sprite.children.list |> List.exists(fun (_,child) -> child :? CloseButtonSprite))
                let closeLocation,_ = tabSprite.children.list |> List.find(fun (_,child) -> child :? CloseButtonSprite)
                let point = tabLocation.add(closeLocation).add(Pt(1,1))
                check (strip.tryHit(point) |> Option.exists(fun (_,part) -> part=TabClose)) "Strip does not route the full close-button region to close"
    finally Dpi.set originalDpi
    use tabBitmap = tabImage.bitmap
    use rendered = TabShadow.render tabBitmap.Width tabBitmap.Height (TabShadow.silhouette tabBitmap) padding
    use preview = new Bitmap(540,260)
    do
        use g = Graphics.FromImage(preview)
        g.Clear(Color.White)
        use dark = new SolidBrush(Color.FromArgb(45,48,53))
        g.FillRectangle(dark, 0, 130, 540, 130)
        for y in [55;185] do
            g.FillRectangle(Brushes.WhiteSmoke, 30, y + tabBitmap.Height, 480, 48)
            g.DrawImage(rendered, 60-padding, y-padding)
            g.DrawImage(tabBitmap, 60, y)
    let previewPath = IO.Path.Combine(__SOURCE_DIRECTORY__, "Debug", "shadow-preview.png")
    preview.Save(previewPath, ImageFormat.Png)
    let downTabs = { ts with direction=TabDown }
    use downBitmap = downTabs.render.bitmap
    use downRendered = TabShadow.renderForDirection downBitmap.Width downBitmap.Height (TabShadow.silhouette downBitmap) padding TabDown
    use downPreview = new Bitmap(540,110)
    do
        use g = Graphics.FromImage(downPreview)
        g.Clear(Color.WhiteSmoke)
        g.DrawImage(downRendered, 60-padding, 10)
        g.DrawImage(downBitmap, 60, 10)
    downPreview.Save(IO.Path.Combine(__SOURCE_DIRECTORY__, "Debug", "shadow-down-preview.png"), ImageFormat.Png)
    printfn "Rendering checks passed. Preview: %s" previewPath

    // Real HWNDs outside the desktop: ownership, flags, move/hide/restore and cleanup.
    let os = OS()
    let mutable helper : TabShadowWindow option = None
    let handler (msg:Win32Message) =
        let result = msg.def()
        if msg.msg = WindowMessages.WM_WINDOWPOSCHANGED then
            helper |> Option.iter (fun shadow -> shadow.sync())
        result
    let owner = os.createWindow handler WindowsStyles.WS_POPUP WindowsExtendedStyles.WS_EX_LAYERED
    try
        let foreground = os.foreground.hwnd
        let ownerWindow = os.windowFromHwnd(owner.hwnd)
        let layer = new TabShadowWindow(os, owner.hwnd)
        helper <- Some layer
        try
            ownerWindow.update(tabImage, Pt(-10000,-10000), 255uy)
            layer.update(tabImage, 255uy, TabUp)
            let owned = os.windowsInZorder.list |> List.find (fun w -> w.parent.hwnd = owner.hwnd)
            let hwnd = owned.hwnd
            check owned.isVisible "Shadow not shown"
            check (owned.hasStyleEx WindowsExtendedStyles.WS_EX_TRANSPARENT) "Shadow intercepts clicks"
            check (owned.hasStyleEx WindowsExtendedStyles.WS_EX_NOACTIVATE) "Shadow can activate"
            check (owned.hasStyleEx WindowsExtendedStyles.WS_EX_TOOLWINDOW) "Shadow is not a tool window"
            check (not owned.isTopMost) "Shadow is globally topmost"
            let distance = Dpi.scale 15
            check (owned.location.x = -10000-distance) "Wrong initial position"
            // SetWindowPos notifies the owner; layered bitmap updates refresh
            // both layers explicitly, as TabStrip.update does.
            let move x y =
                WinUserApi.SetWindowPos(owner.hwnd, IntPtr.Zero, x, y, 0, 0,
                    SetWindowPosFlags.SWP_NOSIZE ||| SetWindowPosFlags.SWP_NOACTIVATE |||
                    SetWindowPosFlags.SWP_NOZORDER) |> ignore
            move -9900 -9800
            check (owned.location.x = -9900-distance && owned.location.y = -9800-distance) "Shadow did not follow"
            ownerWindow.hide()
            check (not owned.isVisible) "Shadow left behind after hide"
            ownerWindow.showNoActivate()
            check owned.isVisible "Shadow not restored"
            // Simulate Windows hiding the owned popup after a frame update.
            // The deferred activation refresh must recover even with no new bitmap.
            owned.hide()
            check (not owned.isVisible) "Could not simulate hidden owned popup"
            layer.sync()
            check owned.isVisible "Activation sync did not restore the shadow"
            check (ownerWindow.prevZorder.hwnd = hwnd) "Shadow not adjacent to strip"
            layer.hide()
            move -9800 -9700
            check (not owned.isVisible) "Disabled shadow reappeared"
            ownerWindow.update(tabImage, Pt(-9700,-9600), 128uy)
            layer.update(tabImage, 128uy, TabUp)
            check (owned.location.x = -9700-distance && owned.location.y = -9600-distance) "Layered update did not follow"
            check (os.foreground.hwnd = foreground) "Shadow changed foreground"
            layer.update(tabImage, 255uy, TabDown)
            check (owned.location.y = -9600) "Down shadow offset is wrong"
            move -9600 -9500
            check (owned.location.y = -9500) "Down shadow did not follow"
            layer.update(tabImage, 255uy, TabUp)
            check (owned.location.y = -9500-distance) "Restore did not reset shadow direction"
            (layer :> IDisposable).Dispose()
            helper <- None
            check (not (WinUserApi.IsWindow(hwnd))) "Shadow HWND leaked"
            printfn "Native window lifecycle checks passed."
        finally
            if helper.IsSome then
                helper <- None
                (layer :> IDisposable).Dispose()
    finally
        (owner :?> IDisposable).Dispose()
main()
