namespace Bemo
open System.Collections.Generic

/// Japanese for every English/Chinese pair written with Localization.text, keyed by the
/// English text. A missing entry falls back to English. Strings built with sprintf use
/// Localization.text3 at the call site instead.
module LocalizationJa =
    let table : IDictionary<string,string> =
        dict [
            // Messages
            "Shortcut unavailable", "ショートカットを使用できません"
            "WindowTabs is already running.", "WindowTabs は既に実行中です。"
            "WindowTabs could not continue", "WindowTabs を続行できません"
            "Settings save failed", "設定を保存できませんでした"
            "Settings error", "設定エラー"
            "Invalid colour. Enter six hexadecimal digits.", "色が無効です。16 進数 6 桁で入力してください。"
            "Workspace restore", "ワークスペースの復元"
            "Invalid workspace setting", "ワークスペースの設定が無効です"
            "Operation failed", "操作に失敗しました"
            // Tab context menu
            "Expand tabs", "タブを展開"
            "Shrink tabs", "タブを縮小"
            "Align tabs", "タブの配置"
            "Left", "左"
            "Center", "中央"
            "Right", "右"
            "Auto-hide tabs when maximized", "最大化時にタブを自動的に隠す"
            "New window", "新しいウィンドウ"
            "Combine icons in taskbar", "タスクバーのアイコンをまとめる"
            "Rename tab", "タブ名を変更"
            "Restore tab name", "タブ名を元に戻す"
            "Close", "閉じる"
            "Close others", "他を閉じる"
            "Close all", "すべて閉じる"
            "Settings...", "設定..."
            // Settings window
            "General", "全般"
            "Appearance", "外観"
            "Shortcuts", "ショートカット"
            "App rules", "アプリのルール"
            "Workspaces", "ワークスペース"
            "About & diagnostics", "バージョン情報と診断"
            "WindowTabs Settings", "WindowTabs の設定"
            "Search settings", "設定を検索"
            "Search suggestions", "検索候補"
            "Search results", "検索結果"
            "No matching settings.", "一致する設定はありません。"
            "Search", "検索"
            "Language", "言語"
            "Follow Windows", "Windows に従う"
            "Follow Windows or choose a language.", "Windows の設定に従うか、言語を選択します。"
            // General
            "Startup and defaults", "起動と既定の設定"
            "Tab behaviour", "タブの動作"
            "Taskbar and window switching", "タスクバーとウィンドウの切り替え"
            "Start with Windows", "Windows と同時に起動"
            "Start WindowTabs when you sign in to Windows.", "Windows にサインインしたときに WindowTabs を起動します。"
            "Enable tabs by default", "既定でタブを有効にする"
            "Applies to apps without a rule in App rules.", "「アプリのルール」で個別に設定していないアプリに適用されます。"
            "Dim inactive groups", "非アクティブなグループを淡色表示"
            "Make tabs in inactive groups translucent.", "アクティブでないグループのタブを半透明にします。"
            "Auto-hide tabs when maximized", "最大化時にタブを自動的に隠す"
            "Move the pointer to the top of the window to show the tabs.", "ポインターをウィンドウの上端に移動するとタブを表示します。"
            "Tab position", "タブの位置"
            "Choose where tabs appear above the window.", "ウィンドウ上部でのタブの位置を選択します。"
            "Combine taskbar icons", "タスクバーのアイコンをまとめる"
            "Use WindowTabs for Alt+Tab", "Alt+Tab に WindowTabs を使う"
            "Group windows in the switcher", "切り替え画面でウィンドウをグループ化"
            // Appearance
            "Theme", "テーマ"
            "Choose system, light, or dark mode.", "システム、ライト、ダークから選択します。"
            "System", "システム"
            "Light", "ライト"
            "Dark", "ダーク"
            "File Explorer theme preview", "エクスプローラーのテーマのプレビュー"
            "Dark theme · Tab colours", "ダークテーマ · タブの色"
            "Light theme · Tab colours", "ライトテーマ · タブの色"
            "Colour preset", "配色プリセット"
            "Custom", "カスタム"
            "Reset this palette", "この配色をリセット"
            "Active tab", "アクティブなタブ"
            "Hovered tab", "ホバー中のタブ"
            "Inactive tab", "非アクティブなタブ"
            "Text and close button", "文字と閉じるボタン"
            "Separator", "区切り線"
            "Flashing tab", "点滅するタブ"
            "Tab layout", "タブのレイアウト"
            "Sizes stay the same when you switch themes.", "テーマを切り替えてもサイズは変わりません。"
            "Reset tab layout", "タブのレイアウトをリセット"
            "Tab height", "タブの高さ"
            "Maximum tab width", "タブの最大幅"
            "Tab spacing", "タブの間隔"
            "Space between neighbouring tabs.", "隣り合うタブの間隔です。"
            "Side margin", "左右の余白"
            "Space between the tabs and the window edges. With centered tabs, this takes effect when the tabs fill the row.",
                "タブとウィンドウの左右の端との間隔です。中央揃えの場合は、タブが行いっぱいになったときに反映されます。"
            "Default", "既定"
            "Ocean", "オーシャン"
            "Forest", "フォレスト"
            "Slate", "スレート"
            "Teal", "ティール"
            "Sand", "サンド"
            "Amber", "アンバー"
            "Rose", "ローズ"
            "Plum", "プラム"
            // Shortcuts
            "Keyboard", "キーボード"
            "Mouse", "マウス"
            "Click a shortcut, then press the new combination. Esc cancels; × or Backspace removes it.",
                "ショートカットをクリックして、新しいキーの組み合わせを押します。Esc でキャンセル、× または Backspace で削除します。"
            "Restore default shortcuts", "既定のショートカットに戻す"
            "Next tab", "次のタブ"
            "Switch to the next window in the group.", "グループ内の次のウィンドウに切り替えます。"
            "Previous tab", "前のタブ"
            "Switch to the previous window in the group.", "グループ内の前のウィンドウに切り替えます。"
            "Switch tabs by number", "番号でタブを切り替え"
            "Use Ctrl + number to select a tab. Restart WindowTabs after changing this option.",
                "Ctrl + 数字キーでタブを選択します。変更後は WindowTabs を再起動してください。"
            "Activate on hover", "ホバーでアクティブにする"
            "Switch windows when the pointer rests on a tab.", "タブにポインターを置くとウィンドウを切り替えます。"
            "Shift + scroll to switch tabs", "Shift + スクロールでタブを切り替え"
            "Hold Shift and scroll over a grouped window to switch tabs. You can also scroll over the tab strip without holding Shift.",
                "グループ化されたウィンドウ上で Shift を押しながらスクロールするとタブを切り替えます。タブバー上では Shift を押さずにスクロールできます。"
            // Shortcut field (kept short to fit)
            "Already set", "設定済み"
            "Include Ctrl or Alt", "Ctrl か Alt が必要です"
            "Press a shortcut…", "キーを押してください…"
            "Not set", "未設定"
            "In use by another app", "他のアプリで使用中"
            // App rules, workspaces, diagnostics
            "Running apps are listed here. Choose which get tabs and which are grouped automatically; expand an app to see its windows.",
                "実行中のアプリの一覧です。タブを表示するアプリと自動的にグループ化するアプリを選択します。アプリを展開するとウィンドウが表示されます。"
            "Save the current window groups as a workspace and restore them later. Edit a window to change how its title is matched.",
                "現在のウィンドウグループをワークスペースとして保存し、後で復元できます。ウィンドウを編集すると、タイトルの一致方法を変更できます。"
            "Choose apps for tabs and automatic grouping.", "タブと自動グループ化を使うアプリを選択します。"
            "Save and restore window layouts.", "ウィンドウの配置を保存して復元します。"
            "Version and troubleshooting information.", "バージョンとトラブルシューティングの情報。"
            "Scan failed: ", "スキャンに失敗しました: "
            "Scanning…", "スキャン中…"
            "Attach this report to bug reports. It omits window titles, paths and license data.", "不具合を報告するときはこのレポートを添付してください。ウィンドウのタイトル、パス、ライセンス情報は含まれません。"
            "Saved.", "保存しました。"
            "Refresh", "更新"
            "Copy report", "レポートをコピー"
            "Report copied.", "レポートをコピーしました。"
            "Save report", "レポートを保存"
            "Export settings", "設定をエクスポート"
        ]
